//! Translates parsed scripts ([`script::Script`]) into Rust source that
//! runs exactly as [`script::interp`] runs them: the same calls on the
//! [`Host`](script::interp::Host) in the same order with the same
//! arguments, the same variable reads and writes, and the same
//! [`Flow`](script::interp::Flow). The generated code calls the
//! interpreter's own primitives ([`script::interp::apply`], `var`, `set`,
//! `call_function`), so the two can't disagree on what an operator or a
//! variable means; only the walk over statements and the expression stack
//! is compiled away. [`parity`] checks that claim by running both.
//!
//! The expression stack is resolved while generating: every value that
//! touches the host (a variable, a function) becomes a `let` in the order
//! the game's stored form works it out, operators nest over those, and a
//! function whose value the host can't work out stops the run where the
//! interpreter would. Values left below the top are worked out and
//! dropped, as in [`script::interp::eval`].
//!
//! The generated code is built from the user's own plugins on their
//! machine (see the `scriptgen` binary) and isn't part of this repository.

pub mod parity;

use std::fmt::Write as _;

use script::{Arg, Call, Expr, Item, Op, Script, Stmt, VarKind};

/// The Rust module for one script: its source text (kept for provenance
/// and the parity check), variables, block headers, and a function per
/// block plus one for statements outside any block.
pub fn module(script: &Script, source: &str, doc: &str) -> String {
    let mut g = Gen::default();
    let mut fns = String::new();
    for (i, block) in script.blocks.iter().enumerate() {
        fns += &g.function(&format!("block_{i}"), &block.body, false);
    }
    fns += &g.function("run_body", &script.body, true);

    let mut out = String::new();
    for line in doc.lines() {
        let _ = writeln!(out, "//! {line}");
    }
    out += "//! Generated by `scriptgen` from the plugin; regenerate rather than edit.\n\n";
    out += "use script::interp::{self, Flow, Host, Locals};\n";
    out += "use script::{Arg, Block, Call, Op, VarKind};\n";
    out += "use std::sync::OnceLock;\n\n";
    let _ = writeln!(out, "pub const SOURCE: &str = {};\n", raw_string(source));
    out += "pub const VARIABLES: &[(VarKind, &str)] = &[\n";
    for (kind, name) in &script.variables {
        let _ = writeln!(out, "    ({}, {name:?}),", var_kind(*kind));
    }
    out += "];\n\n";

    out += "fn calls() -> &'static [Call] {\n";
    out += "    static CALLS: OnceLock<Vec<Call>> = OnceLock::new();\n";
    out += "    CALLS.get_or_init(|| {\n        vec![\n";
    for call in &g.calls {
        let _ = writeln!(out, "            {call},");
    }
    out += "        ]\n    })\n}\n\n";

    out += "/// The blocks' headers (`Begin <kind> [args]`), bodies compiled below.\n";
    out += "pub fn blocks() -> &'static [Block] {\n";
    out += "    static BLOCKS: OnceLock<Vec<Block>> = OnceLock::new();\n";
    out += "    BLOCKS.get_or_init(|| {\n        vec![\n";
    for block in &script.blocks {
        let _ = writeln!(
            out,
            "            Block {{ kind: {:?}.into(), args: vec![{}], body: Vec::new() }},",
            block.kind,
            args(&block.args)
        );
    }
    out += "        ]\n    })\n}\n\n";

    out += "/// As [`interp::run_blocks`]: every block of `kind` that `matches`, in\n";
    out += "/// order, until one doesn't finish.\n";
    out += "pub fn run_blocks(\n    kind: &str,\n    matches: &dyn Fn(&Block) -> bool,\n";
    out += "    locals: &mut Locals,\n    host: &mut dyn Host,\n) {\n";
    out += "    for (i, block) in blocks().iter().enumerate() {\n";
    out +=
        "        if !(block.kind == kind && matches(block)) {\n            continue;\n        }\n";
    out += "        let flow = match i {\n";
    for i in 0..script.blocks.len() {
        let _ = writeln!(out, "            {i} => block_{i}(locals, host),");
    }
    out += "            _ => Flow::Done,\n        };\n";
    out += "        if flow != Flow::Done {\n            break;\n        }\n    }\n}\n\n";
    out += &fns;
    out
}

#[derive(Default)]
struct Gen {
    /// Every call, as Rust that builds it; referred to by index.
    calls: Vec<String>,
    out: String,
    depth: usize,
    temp: usize,
    label: usize,
}

impl Gen {
    fn function(&mut self, name: &str, body: &[Stmt], public: bool) -> String {
        self.out.clear();
        self.depth = 1;
        self.temp = 0;
        self.label = 0;
        self.stmts(body);
        let vis = if public { "pub " } else { "" };
        format!(
            "{vis}fn {name}(locals: &mut Locals, host: &mut dyn Host) -> Flow {{\n    let c = calls();\n{}    Flow::Done\n}}\n\n",
            self.out
        )
    }

    fn line(&mut self, text: &str) {
        for _ in 0..self.depth {
            self.out += "    ";
        }
        self.out += text;
        self.out += "\n";
    }

    fn stmts(&mut self, stmts: &[Stmt]) {
        for stmt in stmts {
            self.stmt(stmt);
        }
    }

    fn stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Set { target, value } => {
                let v = self.expr(value);
                self.line(&format!(
                    "interp::set(&{}, {v}, locals, host);",
                    path(target)
                ));
            }
            Stmt::If {
                branches,
                otherwise,
            } => {
                let label = self.label;
                self.label += 1;
                self.line(&format!("'if{label}: {{"));
                self.depth += 1;
                for (cond, body) in branches {
                    let v = self.expr(cond);
                    self.line(&format!("if {v} != 0.0 {{"));
                    self.depth += 1;
                    self.stmts(body);
                    self.line(&format!("break 'if{label};"));
                    self.depth -= 1;
                    self.line("}");
                }
                if let Some(body) = otherwise {
                    self.stmts(body);
                }
                self.depth -= 1;
                self.line("}");
            }
            Stmt::Return => self.line("return Flow::Returned;"),
            Stmt::Call(call) => {
                // A statement's own value isn't needed: one the host can't
                // carry out is skipped.
                let i = self.call(call);
                self.line(&format!(
                    "let _ = interp::call_function(&c[{i}], locals, host);"
                ));
            }
        }
    }

    /// Emits the `let`s an expression needs, in the stored order, and
    /// returns the Rust expression for its value.
    fn expr(&mut self, e: &Expr) -> String {
        let mut stack: Vec<String> = Vec::new();
        for item in &e.0 {
            let value = match item {
                Item::Number(n) => number(*n),
                Item::Str(_) => "0.0".to_string(),
                Item::Var(p) => {
                    let t = self.temp();
                    self.line(&format!(
                        "let {t} = interp::var(&{}, locals, host);",
                        path(p)
                    ));
                    t
                }
                Item::Call(call) => {
                    let i = self.call(call);
                    let t = self.temp();
                    self.line(&format!(
                        "let Some({t}) = interp::call_function(&c[{i}], locals, host) else {{ return Flow::Stopped; }};"
                    ));
                    t
                }
                Item::Op(op @ (Op::Neg | Op::Not)) => {
                    let y = stack.pop().unwrap_or_else(|| "0.0".into());
                    format!("interp::apply({}, 0.0, {y})", op_name(*op))
                }
                Item::Op(op) => {
                    let y = stack.pop().unwrap_or_else(|| "0.0".into());
                    let x = stack.pop().unwrap_or_else(|| "0.0".into());
                    format!("interp::apply({}, {x}, {y})", op_name(*op))
                }
            };
            stack.push(value);
        }
        stack.pop().unwrap_or_else(|| "0.0".into())
    }

    fn temp(&mut self) -> String {
        self.temp += 1;
        format!("v{}", self.temp)
    }

    fn call(&mut self, call: &Call) -> usize {
        let text = format!(
            "Call {{ function: {} /* {} */, on: {}, args: vec![{}] }}",
            call.function,
            script::function_name(call.function),
            match &call.on {
                Some(on) => format!("Some({on:?}.into())"),
                None => "None".into(),
            },
            args(&call.args)
        );
        self.calls.push(text);
        self.calls.len() - 1
    }
}

fn args(args: &[Arg]) -> String {
    args.iter()
        .map(|a| match a {
            Arg::Word(w) => format!("Arg::Word({w:?}.into())"),
            Arg::Number(n) => format!("Arg::Number({})", number(*n)),
            Arg::Str(s) => format!("Arg::Str({s:?}.into())"),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn path(p: &[String]) -> String {
    format!(
        "[{}]",
        p.iter()
            .map(|s| format!("{s:?}"))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

/// An `f64` literal that reads back as exactly the same value.
fn number(n: f64) -> String {
    let s = format!("{n:?}");
    let s = if s.contains(['.', 'e']) {
        s
    } else {
        format!("{s}.0")
    };
    if n.is_sign_negative() {
        format!("({s})")
    } else {
        s
    }
}

fn op_name(op: Op) -> &'static str {
    match op {
        Op::Or => "Op::Or",
        Op::And => "Op::And",
        Op::Eq => "Op::Eq",
        Op::Ne => "Op::Ne",
        Op::Lt => "Op::Lt",
        Op::Le => "Op::Le",
        Op::Gt => "Op::Gt",
        Op::Ge => "Op::Ge",
        Op::Add => "Op::Add",
        Op::Sub => "Op::Sub",
        Op::Mul => "Op::Mul",
        Op::Div => "Op::Div",
        Op::Mod => "Op::Mod",
        Op::Neg => "Op::Neg",
        Op::Not => "Op::Not",
    }
}

fn var_kind(k: VarKind) -> &'static str {
    match k {
        VarKind::Integer => "VarKind::Integer",
        VarKind::Float => "VarKind::Float",
        VarKind::Ref => "VarKind::Ref",
    }
}

/// A raw string literal with enough `#`s for the text.
fn raw_string(text: &str) -> String {
    let mut hashes = 1;
    while text.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let h = "#".repeat(hashes);
    format!("r{h}\"{text}\"{h}")
}

/// A Rust identifier from an editor ID or other name.
pub fn ident(text: &str) -> String {
    let mut s: String = text
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    if s.is_empty() || s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn numbers_read_back_exactly() {
        assert_eq!(number(1.0), "1.0");
        assert_eq!(number(0.1), "0.1");
        assert_eq!(number(-2.5), "(-2.5)");
        assert_eq!(number(1e-7), "1e-7");
    }

    #[test]
    fn raw_strings_hold_quotes_and_hashes() {
        assert_eq!(raw_string("a"), "r#\"a\"#");
        assert_eq!(raw_string("say \"#hi\""), "r##\"say \"#hi\"\"##");
    }

    #[test]
    fn identifiers() {
        assert_eq!(ident("NVDLC01Foo-Bar"), "nvdlc01foo_bar");
        assert_eq!(ident("01005321"), "_01005321");
    }

    #[test]
    fn values_left_below_the_top_are_worked_out_in_order() {
        let script = script::parse("short a\nset a to GetStage VMQ 110 != 1").unwrap();
        let m = module(&script, "", "test");
        // The call is made (and can stop the run) before the comparison.
        let call = m.find("call_function(&c[0]").unwrap();
        let cmp = m.find("interp::apply(Op::Ne, 110.0, 1.0)").unwrap();
        assert!(call < cmp, "{m}");
    }
}
