//! `scriptgen <plugin> <out-dir> [crate-name]`: translates every script
//! in a plugin (script records, and the result scripts in dialogue lines,
//! quest stages, packages, terminals and the rest: every `SCTX`) into a
//! Rust crate at `out-dir`, with a parity test against the interpreter.
//! The crate is built from your own game files and stays on your machine;
//! keep it out of this repository.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use esm::{FourCC, Plugin};

const SCTX: FourCC = FourCC::new(b"SCTX");

struct Entry {
    module: String,
    kind: String,
    form_id: u32,
    editor_id: String,
    index: usize,
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let (Some(plugin_path), Some(out)) = (args.first(), args.get(1)) else {
        eprintln!("usage: scriptgen <plugin.esm> <out-dir> [crate-name]");
        return ExitCode::FAILURE;
    };
    let plugin_path = Path::new(plugin_path);
    let plugin_file = plugin_path
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();
    let crate_name = args.get(2).cloned().unwrap_or_else(|| {
        scriptgen::ident(
            plugin_path
                .file_stem()
                .unwrap_or_default()
                .to_str()
                .unwrap_or("scripts"),
        )
    });
    match run(plugin_path, &plugin_file, Path::new(out), &crate_name) {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("scriptgen: {e}");
            ExitCode::FAILURE
        }
    }
}

fn run(plugin_path: &Path, plugin_file: &str, out: &Path, crate_name: &str) -> Result<(), String> {
    let plugin =
        Plugin::open(plugin_path).map_err(|e| format!("{}: {e}", plugin_path.display()))?;
    let scripts_dir = out.join("src").join("scripts");
    if scripts_dir.exists() {
        fs::remove_dir_all(&scripts_dir).map_err(|e| e.to_string())?;
    }
    fs::create_dir_all(&scripts_dir).map_err(|e| e.to_string())?;
    fs::create_dir_all(out.join("tests")).map_err(|e| e.to_string())?;

    let mut entries = Vec::new();
    let mut failures = Vec::new();
    for entry in plugin.records() {
        let record = match plugin.record(entry) {
            Ok(r) => r,
            Err(e) => {
                failures.push(format!(
                    "{} {}: unreadable: {e}",
                    entry.header.kind, entry.header.form_id
                ));
                continue;
            }
        };
        let kind = entry.header.kind.to_string();
        let form_id = entry.header.form_id;
        let editor_id = record.editor_id().unwrap_or_default();
        for (index, sub) in record.get_all(SCTX).enumerate() {
            let source = esm::text::decode_cp1252(&sub.data);
            let label = format!("{kind} {editor_id} [{form_id}] script {index}");
            let parsed = match script::parse(&source) {
                Ok(p) => p,
                Err(e) => {
                    failures.push(format!("{label}: {e}"));
                    continue;
                }
            };
            let module = scriptgen::ident(&if editor_id.is_empty() {
                format!("{kind}_{form_id}_{index}")
            } else {
                format!("{kind}_{editor_id}_{form_id}_{index}")
            });
            let doc = format!("{label}, from {plugin_file}.");
            let code = scriptgen::module(&parsed, &source, &doc);
            fs::write(scripts_dir.join(format!("{module}.rs")), code).map_err(|e| e.to_string())?;
            entries.push(Entry {
                module,
                kind: kind.clone(),
                form_id: form_id.0,
                editor_id: editor_id.clone(),
                index,
            });
        }
    }

    write_crate(out, crate_name, plugin_file, &entries).map_err(|e| e.to_string())?;
    let mut report = format!(
        "# {crate_name}\n\nGenerated by `scriptgen` from `{plugin_file}`: {} scripts translated, {} not.\n",
        entries.len(),
        failures.len()
    );
    let mut by_kind = std::collections::BTreeMap::<&str, usize>::new();
    for e in &entries {
        *by_kind.entry(e.kind.as_str()).or_default() += 1;
    }
    report += "\n| Record | Scripts |\n|---|---|\n";
    for (k, n) in by_kind {
        let _ = writeln!(report, "| {k} | {n} |");
    }
    if !failures.is_empty() {
        report += "\n## Not translated (the parser doesn't accept them)\n\n";
        for f in &failures {
            let _ = writeln!(report, "- {f}");
        }
    }
    fs::write(out.join("REPORT.md"), &report).map_err(|e| e.to_string())?;
    println!(
        "{}: {} scripts translated, {} not (see REPORT.md)",
        out.display(),
        entries.len(),
        failures.len()
    );
    Ok(())
}

fn write_crate(
    out: &Path,
    name: &str,
    plugin_file: &str,
    entries: &[Entry],
) -> std::io::Result<()> {
    let crates = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crates directory")
        .canonicalize()?;
    let dep = |c: &str| {
        let p = crates.join(c).to_string_lossy().replace('\\', "/");
        let p = p.strip_prefix("//?/").unwrap_or(&p).to_string();
        format!("{c} = {{ path = {p:?} }}")
    };
    fs::write(
        out.join("Cargo.toml"),
        format!(
            "# Generated by scriptgen from {plugin_file}. Built from your own game files: keep it private.\n\
             [package]\nname = {name:?}\nversion = \"0.1.0\"\nedition = \"2021\"\npublish = false\n\n\
             [dependencies]\n{}\n\n[dev-dependencies]\n{}\n\n\
             # Its own workspace, not part of nv-rs.\n[workspace]\n",
            dep("script"),
            dep("scriptgen")
        ),
    )?;
    fs::write(out.join(".gitignore"), "target/\n")?;

    let mut mods = String::from("//! One module per script. Generated by `scriptgen`.\n\n");
    for e in entries {
        let _ = writeln!(mods, "pub mod {};", e.module);
    }
    fs::write(out.join("src").join("scripts.rs"), mods)?;

    let mut lib = format!(
        "//! Every script in `{plugin_file}`, translated to Rust by `scriptgen`. Each runs\n\
         //! exactly as `script::interp` runs its source (see `tests/parity.rs`).\n\
         //! Form IDs are as the plugin writes them (its own masters' numbering).\n\n\
         #![allow(unused_variables, unused_labels, unused_parens, unreachable_code, unused_imports, clippy::all)]\n\n\
         pub mod scripts;\n\n\
         use script::interp::{{Flow, Host, Locals}};\n\
         use script::{{Block, VarKind}};\n\n\
         /// One translated script.\n\
         pub struct Compiled {{\n\
         \x20   /// The record holding it (`SCPT`, `INFO`, `QUST`, `TERM`, …).\n\
         \x20   pub kind: &'static str,\n\
         \x20   pub form_id: u32,\n\
         \x20   pub editor_id: &'static str,\n\
         \x20   /// Which of the record's scripts (`SCTX`), in file order.\n\
         \x20   pub index: usize,\n\
         \x20   pub source: &'static str,\n\
         \x20   pub variables: &'static [(VarKind, &'static str)],\n\
         \x20   pub blocks: fn() -> &'static [Block],\n\
         \x20   pub run_blocks: fn(&str, &dyn Fn(&Block) -> bool, &mut Locals, &mut dyn Host),\n\
         \x20   pub run_body: fn(&mut Locals, &mut dyn Host) -> Flow,\n\
         }}\n\n\
         pub static ALL: &[Compiled] = &[\n"
    );
    for e in entries {
        let m = &e.module;
        let _ = writeln!(
            lib,
            "    Compiled {{ kind: {:?}, form_id: 0x{:08X}, editor_id: {:?}, index: {}, \
             source: scripts::{m}::SOURCE, variables: scripts::{m}::VARIABLES, blocks: scripts::{m}::blocks, \
             run_blocks: scripts::{m}::run_blocks, run_body: scripts::{m}::run_body }},",
            e.kind, e.form_id, e.editor_id, e.index
        );
    }
    lib += "];\n\n\
            /// A script record's (`SCPT`) translation, by editor ID (any case).\n\
            pub fn script(editor_id: &str) -> Option<&'static Compiled> {\n\
            \x20   ALL.iter()\n\
            \x20       .find(|c| c.kind == \"SCPT\" && c.editor_id.eq_ignore_ascii_case(editor_id))\n\
            }\n\n\
            /// A record's scripts, by form ID.\n\
            pub fn of_record(form_id: u32) -> impl Iterator<Item = &'static Compiled> {\n\
            \x20   ALL.iter().filter(move |c| c.form_id == form_id)\n\
            }\n";
    fs::write(out.join("src").join("lib.rs"), lib)?;

    fs::write(
        out.join("tests").join("parity.rs"),
        format!(
            "//! Every translated script runs exactly as the interpreter runs its source.\n\n\
             use scriptgen::parity::{{check, Generated}};\n\n\
             #[test]\n\
             fn every_script_matches_the_interpreter() {{\n\
             \x20   let mut failures = Vec::new();\n\
             \x20   for c in {name}::ALL {{\n\
             \x20       let g = Generated {{ variables: c.variables, blocks: c.blocks, run_blocks: c.run_blocks, run_body: c.run_body }};\n\
             \x20       if let Err(e) = check(c.source, &g) {{\n\
             \x20           failures.push(format!(\"{{}} {{}} [{{:08X}}] #{{}}: {{e}}\", c.kind, c.editor_id, c.form_id, c.index));\n\
             \x20       }}\n\
             \x20   }}\n\
             \x20   assert!(failures.is_empty(), \"{{}} of {{}} differ:\\n{{}}\", failures.len(), {name}::ALL.len(), failures.join(\"\\n\"));\n\
             }}\n"
        ),
    )?;
    Ok(())
}
