// Exports a fully analysed Ghidra program into browsable text:
//   <out>/src/fnv_XXXXXXXX.c  decompiled C, one file per 64 KB of code address space
//   <out>/functions.tsv        every function: address, size, name, namespace, signature
//   <out>/strings.tsv          defined strings: address, type, value
//   <out>/classes.tsv          classes from MSVC RTTI: type descriptor, vftable addresses, slot counts
//   <out>/imports.tsv          imported functions: dll, name, IAT address
//   <out>/types.h              data types known to the program (structs, enums, typedefs)
// Usage (headless): -postScript ExportFNV.java <out_dir> [--listings-only]
//   --listings-only skips decompilation and only rewrites the .tsv files and types.h
// @category FNV
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

import ghidra.app.decompiler.*;
import ghidra.app.decompiler.parallel.*;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.data.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.symbol.*;
import ghidra.program.util.DefinedStringIterator;
import ghidra.util.task.TaskMonitor;

public class ExportFNV extends GhidraScript {
	private static final long CHUNK = 0x10000;
	private static final int TIMEOUT_SECS = 120;
	private static final int RETRY_TIMEOUT_SECS = 1800;

	private record Result(Function f, String body, boolean ok) {}

	private static Result toResult(Function f, DecompileResults r) {
		if (r.decompileCompleted() && r.getDecompiledFunction() != null) {
			return new Result(f, r.getDecompiledFunction().getC(), true);
		}
		return new Result(f, "/* decompilation failed: " + r.getErrorMessage() + " */\n", false);
	}

	private static String tsv(String s) {
		if (s == null) return "";
		return s.replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n").replace("\r", "\\r");
	}

	private static PrintWriter open(File f) throws IOException {
		return new PrintWriter(new BufferedWriter(
			new OutputStreamWriter(new FileOutputStream(f), StandardCharsets.UTF_8)));
	}

	@Override
	protected void run() throws Exception {
		String[] args = getScriptArgs();
		File out = new File(args.length > 0 ? args[0] : "decomp");
		boolean listingsOnly = args.length > 1 && args[1].equals("--listings-only");
		File src = new File(out, "src");
		src.mkdirs();

		List<Function> funcs = new ArrayList<>();
		for (Function f : currentProgram.getFunctionManager().getFunctions(true)) {
			if (!f.isExternal() && !f.isThunk()) funcs.add(f);
		}
		println("Functions to decompile: " + funcs.size());

		writeFunctions(new File(out, "functions.tsv"));
		writeStrings(new File(out, "strings.tsv"));
		writeClasses(new File(out, "classes.tsv"));
		writeImports(new File(out, "imports.tsv"));
		writeTypes(new File(out, "types.h"));
		if (listingsOnly) return;

		// Group by 64 KB of address space so file names map directly to addresses.
		TreeMap<Long, List<Function>> chunks = new TreeMap<>();
		for (Function f : funcs) {
			long a = f.getEntryPoint().getOffset();
			chunks.computeIfAbsent(a - (a % CHUNK), k -> new ArrayList<>()).add(f);
		}

		DecompileConfigurer cfg = ifc -> {
			DecompileOptions o = new DecompileOptions();
			o.grabFromProgram(currentProgram);
			ifc.setOptions(o);
			ifc.toggleCCode(true);
			ifc.toggleSyntaxTree(false);
			ifc.setSimplificationStyle("decompile");
		};
		DecompilerCallback<Result> cb = new DecompilerCallback<>(currentProgram, cfg) {
			@Override
			public Result process(DecompileResults r, TaskMonitor m) {
				return toResult(r.getFunction(), r);
			}
		};
		cb.setTimeout(TIMEOUT_SECS);

		// Functions that time out in the parallel pass are retried one at a time with a much
		// longer limit; a handful of huge functions need several minutes each.
		DecompInterface retry = new DecompInterface();
		cfg.configure(retry);
		retry.openProgram(currentProgram);

		int done = 0;
		int failed = 0;
		try {
			for (Map.Entry<Long, List<Function>> e : chunks.entrySet()) {
				monitor.checkCancelled();
				File file = new File(src, String.format("fnv_%08X.c", e.getKey()));
				List<Result> res = new ArrayList<>(
					ParallelDecompiler.decompileFunctions(cb, e.getValue(), monitor));
				for (int i = 0; i < res.size(); i++) {
					if (res.get(i).ok()) continue;
					Function f = res.get(i).f();
					println("Retrying " + f.getEntryPoint() + " with a longer timeout");
					res.set(i, toResult(f, retry.decompileFunction(f, RETRY_TIMEOUT_SECS, monitor)));
				}
				res.sort(Comparator.comparing(x -> x.f().getEntryPoint()));
				try (PrintWriter w = open(file)) {
					w.printf("/*%n * Fallout: New Vegas 1.4.0.525 - decompiled code for 0x%08X-0x%08X%n" +
						" * Generated by Ghidra. Names like FUN_xxxxxxxx are auto-generated.%n */%n%n" +
						"#include \"../types.h\"%n%n", e.getKey(), e.getKey() + CHUNK - 1);
					for (Result x : res) {
						if (!x.ok()) failed++;
						w.printf("/* %s  %s */%n%s%n", x.f().getEntryPoint(), x.f().getName(true),
							x.body());
					}
				}
				done += res.size();
				println(String.format("%s: %d functions (%d/%d)", file.getName(), res.size(), done,
					funcs.size()));
			}
		}
		finally {
			cb.dispose();
			retry.dispose();
		}
		println("Done. Decompiled " + done + " functions, " + failed + " failed.");
	}

	private void writeFunctions(File file) throws IOException {
		try (PrintWriter w = open(file)) {
			w.println("address\tsize\tname\tnamespace\tcalling_convention\tsignature");
			for (Function f : currentProgram.getFunctionManager().getFunctions(true)) {
				if (f.isExternal()) continue;
				w.println(String.join("\t", f.getEntryPoint().toString(),
					Long.toString(f.getBody().getNumAddresses()), tsv(f.getName()),
					tsv(f.getParentNamespace().getName(true)), tsv(f.getCallingConventionName()),
					tsv(f.getPrototypeString(true, false))));
			}
		}
	}

	private void writeStrings(File file) throws IOException {
		try (PrintWriter w = open(file)) {
			w.println("address\ttype\tvalue");
			for (Data d : DefinedStringIterator.forProgram(currentProgram)) {
				Object v = d.getValue();
				w.println(String.join("\t", d.getAddress().toString(),
					tsv(d.getDataType().getName()), tsv(v == null ? "" : v.toString())));
			}
		}
	}

	private void writeClasses(File file) throws IOException {
		// One row per class that has an MSVC RTTI type descriptor (after ApplyRtti.java), with
		// its vftable(s) when found.
		SymbolTable st = currentProgram.getSymbolTable();
		Listing listing = currentProgram.getListing();
		TreeMap<String, String[]> rows = new TreeMap<>();
		for (Symbol s : st.getSymbolIterator("RTTI_Type_Descriptor", true)) {
			rows.put(s.getParentNamespace().getName(true),
				new String[] { s.getAddress().toString(), "", "" });
		}
		// A class has one vftable per polymorphic base under multiple inheritance; list them all.
		for (Symbol s : st.getSymbolIterator("vftable", true)) {
			String[] r = rows.computeIfAbsent(s.getParentNamespace().getName(true),
				k -> new String[] { "", "", "" });
			Data d = listing.getDataAt(s.getAddress());
			String slots = d != null && d.isArray() ? Integer.toString(d.getNumComponents()) : "?";
			r[1] = r[1].isEmpty() ? s.getAddress().toString() : r[1] + "," + s.getAddress();
			r[2] = r[2].isEmpty() ? slots : r[2] + "," + slots;
		}
		try (PrintWriter w = open(file)) {
			w.println("class\ttype_descriptor_address\tvftable_addresses\tvftable_slots");
			for (Map.Entry<String, String[]> e : rows.entrySet()) {
				w.println(tsv(e.getKey()) + "\t" + String.join("\t", e.getValue()));
			}
		}
	}

	private void writeImports(File file) throws IOException {
		try (PrintWriter w = open(file)) {
			w.println("library\tname\taddress");
			for (Symbol s : currentProgram.getSymbolTable().getExternalSymbols()) {
				ExternalLocation loc =
					currentProgram.getExternalManager().getExternalLocation(s);
				Reference[] refs = s.getReferences();
				String at = refs.length > 0 ? refs[0].getFromAddress().toString() : "";
				w.println(String.join("\t", tsv(loc == null ? "" : loc.getLibraryName()),
					tsv(s.getName()), at));
			}
		}
	}

	private void writeTypes(File file) throws Exception {
		try (PrintWriter w = open(file)) {
			DataTypeWriter dtw = new DataTypeWriter(currentProgram.getDataTypeManager(), w);
			List<DataType> all = new ArrayList<>();
			currentProgram.getDataTypeManager().getAllDataTypes(all);
			dtw.write(all, monitor);
		}
	}
}
